/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContentTypesImport } from './routes/content-types'
import { Route as ContentManagerImport } from './routes/content-manager'
import { Route as IndexImport } from './routes/index'
import { Route as ContentTypesEntityImport } from './routes/content-types/$entity'
import { Route as ContentManagerEntityImport } from './routes/content-manager/$entity'
import { Route as ContentTypesEntityCreateImport } from './routes/content-types/$entity_.create'
import { Route as ContentManagerEntityCreateImport } from './routes/content-manager/$entity_.create'
import { Route as ContentManagerEntityUpdateIdImport } from './routes/content-manager/$entity_.update.$id'

// Create/Update Routes

const ContentTypesRoute = ContentTypesImport.update({
  path: '/content-types',
  getParentRoute: () => rootRoute,
} as any)

const ContentManagerRoute = ContentManagerImport.update({
  path: '/content-manager',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContentTypesEntityRoute = ContentTypesEntityImport.update({
  path: '/$entity',
  getParentRoute: () => ContentTypesRoute,
} as any)

const ContentManagerEntityRoute = ContentManagerEntityImport.update({
  path: '/$entity',
  getParentRoute: () => ContentManagerRoute,
} as any)

const ContentTypesEntityCreateRoute = ContentTypesEntityCreateImport.update({
  path: '/$entity/create',
  getParentRoute: () => ContentTypesRoute,
} as any)

const ContentManagerEntityCreateRoute = ContentManagerEntityCreateImport.update(
  {
    path: '/$entity/create',
    getParentRoute: () => ContentManagerRoute,
  } as any,
)

const ContentManagerEntityUpdateIdRoute =
  ContentManagerEntityUpdateIdImport.update({
    path: '/$entity/update/$id',
    getParentRoute: () => ContentManagerRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/content-manager': {
      preLoaderRoute: typeof ContentManagerImport
      parentRoute: typeof rootRoute
    }
    '/content-types': {
      preLoaderRoute: typeof ContentTypesImport
      parentRoute: typeof rootRoute
    }
    '/content-manager/$entity': {
      preLoaderRoute: typeof ContentManagerEntityImport
      parentRoute: typeof ContentManagerImport
    }
    '/content-types/$entity': {
      preLoaderRoute: typeof ContentTypesEntityImport
      parentRoute: typeof ContentTypesImport
    }
    '/content-manager/$entity/create': {
      preLoaderRoute: typeof ContentManagerEntityCreateImport
      parentRoute: typeof ContentManagerImport
    }
    '/content-types/$entity/create': {
      preLoaderRoute: typeof ContentTypesEntityCreateImport
      parentRoute: typeof ContentTypesImport
    }
    '/content-manager/$entity/update/$id': {
      preLoaderRoute: typeof ContentManagerEntityUpdateIdImport
      parentRoute: typeof ContentManagerImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ContentManagerRoute.addChildren([
    ContentManagerEntityRoute,
    ContentManagerEntityCreateRoute,
    ContentManagerEntityUpdateIdRoute,
  ]),
  ContentTypesRoute.addChildren([
    ContentTypesEntityRoute,
    ContentTypesEntityCreateRoute,
  ]),
])

/* prettier-ignore-end */
