/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContentTypesImport } from './routes/content-types'
import { Route as ContentManagerImport } from './routes/content-manager'
import { Route as IndexImport } from './routes/index'
import { Route as ContentTypesEntityImport } from './routes/content-types.$entity'

// Create/Update Routes

const ContentTypesRoute = ContentTypesImport.update({
  path: '/content-types',
  getParentRoute: () => rootRoute,
} as any)

const ContentManagerRoute = ContentManagerImport.update({
  path: '/content-manager',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContentTypesEntityRoute = ContentTypesEntityImport.update({
  path: '/$entity',
  getParentRoute: () => ContentTypesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/content-manager': {
      preLoaderRoute: typeof ContentManagerImport
      parentRoute: typeof rootRoute
    }
    '/content-types': {
      preLoaderRoute: typeof ContentTypesImport
      parentRoute: typeof rootRoute
    }
    '/content-types/$entity': {
      preLoaderRoute: typeof ContentTypesEntityImport
      parentRoute: typeof ContentTypesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ContentManagerRoute,
  ContentTypesRoute.addChildren([ContentTypesEntityRoute]),
])

/* prettier-ignore-end */
